import './globals.css';

import Sidebar from'./Components/Sidebar';
import { personalData } from "../Data/page-data.jsx";



export const metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    

      <body  className='flex flex-col sm:flex-row'>
      <Sidebar data={personalData}/>

      
        				<main className='grow-full p-8 sm:p-16 w-full sm:basis-2/3  ml-auto'>
        
        {children}

        
        </main>
        
        </body>
    </html>
  )
}
